# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replica_admin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'replica_admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13replica_admin.proto\x12\x07replica\"\x0f\n\rStatusRequest\"\xa1\x01\n\x0eStatusResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1b\n\x04role\x18\x02 \x01(\x0e\x32\r.replica.Role\x12\x0c\n\x04term\x18\x03 \x01(\x04\x12\x13\n\x0bleader_hint\x18\x04 \x01(\t\x12\x16\n\x0elast_log_index\x18\x05 \x01(\x03\x12\x15\n\rlast_log_term\x18\x06 \x01(\x04\x12\x14\n\x0c\x63ommit_index\x18\x07 \x01(\x03\"r\n\x14SubmitMessageRequest\x12\x11\n\tfrom_user\x18\x01 \x01(\t\x12\x0f\n\x07to_user\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x15\n\rclient_msg_id\x18\x04 \x01(\t\x12\x0c\n\x04text\x18\x05 \x01(\t\"J\n\x15SubmitMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bleader_hint\x18\x02 \x01(\t\x12\x0b\n\x03seq\x18\x03 \x01(\x04\"\\\n\x18QueryConversationRequest\x12\x0e\n\x06user_a\x18\x01 \x01(\t\x12\x0e\n\x06user_b\x18\x02 \x01(\t\x12\x11\n\tafter_seq\x18\x03 \x01(\x04\x12\r\n\x05limit\x18\x04 \x01(\r\"\x83\x01\n\x11\x43onversationEvent\x12\x0b\n\x03seq\x18\x01 \x01(\x04\x12\x11\n\tfrom_user\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x16\n\x0eserver_time_ms\x18\x04 \x01(\x03\x12\x11\n\tclient_id\x18\x05 \x01(\t\x12\x15\n\rclient_msg_id\x18\x06 \x01(\t\"G\n\x19QueryConversationResponse\x12*\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x1a.replica.ConversationEvent*/\n\x04Role\x12\x0c\n\x08\x46OLLOWER\x10\x00\x12\r\n\tCANDIDATE\x10\x01\x12\n\n\x06LEADER\x10\x02\x32\xf5\x01\n\x0cReplicaAdmin\x12\x39\n\x06Status\x12\x16.replica.StatusRequest\x1a\x17.replica.StatusResponse\x12N\n\rSubmitMessage\x12\x1d.replica.SubmitMessageRequest\x1a\x1e.replica.SubmitMessageResponse\x12Z\n\x11QueryConversation\x12!.replica.QueryConversationRequest\x1a\".replica.QueryConversationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replica_admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROLE']._serialized_start=706
  _globals['_ROLE']._serialized_end=753
  _globals['_STATUSREQUEST']._serialized_start=32
  _globals['_STATUSREQUEST']._serialized_end=47
  _globals['_STATUSRESPONSE']._serialized_start=50
  _globals['_STATUSRESPONSE']._serialized_end=211
  _globals['_SUBMITMESSAGEREQUEST']._serialized_start=213
  _globals['_SUBMITMESSAGEREQUEST']._serialized_end=327
  _globals['_SUBMITMESSAGERESPONSE']._serialized_start=329
  _globals['_SUBMITMESSAGERESPONSE']._serialized_end=403
  _globals['_QUERYCONVERSATIONREQUEST']._serialized_start=405
  _globals['_QUERYCONVERSATIONREQUEST']._serialized_end=497
  _globals['_CONVERSATIONEVENT']._serialized_start=500
  _globals['_CONVERSATIONEVENT']._serialized_end=631
  _globals['_QUERYCONVERSATIONRESPONSE']._serialized_start=633
  _globals['_QUERYCONVERSATIONRESPONSE']._serialized_end=704
  _globals['_REPLICAADMIN']._serialized_start=756
  _globals['_REPLICAADMIN']._serialized_end=1001
# @@protoc_insertion_point(module_scope)
